services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/realtorCRM
    command: ["uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - ./app/.env
    depends_on:
      - db
    networks:
      - backend
    container_name: app

  db:
    image: postgres:17.0-alpine3.20
    env_file:
      - ./app/.env
    networks:
      - backend
    container_name: db
    

networks:
  backend: