import asyncio
from datetime import datetime

from sqlalchemy.exc import IntegrityError

from app.infrastructure.db import async_session
from app.infrastructure.models import Listing
from app.infrastructure.models.client_model import Client


async def populate_db():
    session = async_session()

    client_data = Client(
        id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
        full_name="string",
        phone_number="12321321",
        email="dasd@dsa.pl",
    )

    listing_data = [
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Cozy Family House",
            location="Springfield",
            street="742 Evergreen Terrace",
            price=250000,
            area=120,
            property_type="HOUSE",
            description="A charming house perfect for families, with a spacious backyard.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="2",
            build_year="1995",
            created_at=datetime(2023, 3, 15),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Modern Villa",
            location="Seaside Heights",
            street="123 Ocean View Lane",
            price=950000,
            area=300,
            property_type="HOUSE",
            description="A luxurious villa with stunning ocean views, perfect for a getaway.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="3",
            build_year="2010",
            created_at=datetime(2024, 8, 10),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Urban Townhouse",
            location="Downtown City",
            street="456 Central Avenue",
            price=450000,
            area=150,
            property_type="HOUSE",
            description="Modern townhouse in the heart of the city, ideal for young professionals.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="2",
            build_year="2005",
            created_at=datetime(2022, 11, 5),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Country Cottage",
            location="Meadowville",
            street="789 Countryside Road",
            price=200000,
            area=100,
            property_type="HOUSE",
            description="A peaceful cottage surrounded by nature, great for a weekend retreat.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="1",
            build_year="1980",
            created_at=datetime(2025, 1, 15),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Luxury Estate",
            location="Beverly Hills",
            street="90210 Elite Drive",
            price=2500000,
            area=500,
            property_type="HOUSE",
            description="A lavish estate with unmatched elegance and stunning design.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="3",
            build_year="2015",
            created_at=datetime(2023, 4, 12),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Seaside Cottage",
            location="Bayview",
            street="321 Shoreline Road",
            price=320000,
            area=130,
            property_type="HOUSE",
            description="A cozy seaside cottage perfect for peaceful living by the water.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="1",
            build_year="1990",
            created_at=datetime(2022, 9, 20),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Penthouse Loft",
            location="City Skyline",
            street="789 Highrise Blvd",
            price=1200000,
            area=250,
            property_type="HOUSE",
            description="A stunning penthouse with panoramic city views and luxury amenities.",
            transaction_type="SELL",
            floor="15",
            num_of_floors="15",
            build_year="2020",
            created_at=datetime(2024, 6, 1),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Charming Villa",
            location="Countryside Retreat",
            street="456 Willow Lane",
            price=700000,
            area=200,
            property_type="HOUSE",
            description="An elegant villa with beautiful gardens and serene surroundings.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="2",
            build_year="2010",
            created_at=datetime(2025, 1, 5),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Rustic Cabin",
            location="Mountain View",
            street="123 Pinewood Trail",
            price=180000,
            area=90,
            property_type="HOUSE",
            description="A rustic cabin in the mountains with breathtaking views.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="1",
            build_year="1985",
            created_at=datetime(2023, 11, 2),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Suburban Home",
            location="Maple Grove",
            street="888 Maple Avenue",
            price=400000,
            area=160,
            property_type="HOUSE",
            description="A modern suburban home in a family-friendly neighborhood.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="2",
            build_year="2000",
            created_at=datetime(2024, 2, 10),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Eco-Friendly Bungalow",
            location="Greenfield",
            street="100 Solar Street",
            price=300000,
            area=140,
            property_type="HOUSE",
            description="An environmentally conscious home with modern solar features.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="1",
            build_year="2018",
            created_at=datetime(2022, 10, 14),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Downtown Flat",
            location="Urban Center",
            street="45 Main Street",
            price=600000,
            area=180,
            property_type="HOUSE",
            description="A stylish flat in the heart of downtown, close to all amenities.",
            transaction_type="SELL",
            floor="4",
            num_of_floors="6",
            build_year="2017",
            created_at=datetime(2023, 5, 19),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Modern Townhouse",
            location="Lakeside",
            street="12 Riverbank Road",
            price=520000,
            area=150,
            property_type="HOUSE",
            description="A chic townhouse near the lake, ideal for a growing family.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="2",
            build_year="2005",
            created_at=datetime(2024, 7, 30),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Historic Manor",
            location="Old Town",
            street="10 Heritage Lane",
            price=850000,
            area=280,
            property_type="HOUSE",
            description="A historic manor with unique architectural details and charm.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="3",
            build_year="1920",
            created_at=datetime(2025, 1, 19),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Urban Loft",
            location="City Center",
            street="1001 Broadway",
            price=800000,
            area=210,
            property_type="HOUSE",
            description="A modern loft in a prime urban location with an open-concept layout.",
            transaction_type="SELL",
            floor="5",
            num_of_floors="6",
            build_year="2019",
            created_at=datetime(2023, 12, 9),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Coastal Retreat",
            location="Harborview",
            street="789 Beach Road",
            price=650000,
            area=180,
            property_type="HOUSE",
            description="A relaxing coastal retreat, just steps from the beach.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="2",
            build_year="2008",
            created_at=datetime(2024, 3, 1),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Spacious Apartment",
            location="East End",
            street="500 Greenway Avenue",
            price=350000,
            area=130,
            property_type="HOUSE",
            description="A spacious apartment offering modern amenities in an up-and-coming neighborhood.",
            transaction_type="SELL",
            floor="3",
            num_of_floors="5",
            build_year="2010",
            created_at=datetime(2022, 8, 13),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Luxury Penthouse",
            location="Skyline Ridge",
            street="888 Summit Street",
            price=2500000,
            area=350,
            property_type="HOUSE",
            description="A breathtaking penthouse with floor-to-ceiling windows and a private rooftop.",
            transaction_type="SELL",
            floor="25",
            num_of_floors="25",
            build_year="2022",
            created_at=datetime(2024, 10, 30),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Suburban Retreat",
            location="Willow Creek",
            street="234 Elmwood Drive",
            price=480000,
            area=160,
            property_type="HOUSE",
            description="A charming suburban home, perfect for families with children.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="2",
            build_year="2014",
            created_at=datetime(2022, 12, 5),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Farmhouse",
            location="Sunny Acres",
            street="456 Harvest Lane",
            price=550000,
            area=220,
            property_type="HOUSE",
            description="A spacious farmhouse with expansive farmland and a peaceful atmosphere.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="2",
            build_year="1980",
            created_at=datetime(2023, 11, 21),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Mountain View Cabin",
            location="Rocky Ridge",
            street="123 Alpine Road",
            price=700000,
            area=200,
            property_type="HOUSE",
            description="A rustic cabin in the mountains with stunning panoramic views.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="1",
            build_year="1995",
            created_at=datetime(2023, 7, 15),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Modern Duplex",
            location="Greenwich Park",
            street="200 Park Avenue",
            price=675000,
            area=170,
            property_type="HOUSE",
            description="A sleek, modern duplex perfect for a family or shared living.",
            transaction_type="SELL",
            floor="2",
            num_of_floors="2",
            build_year="2015",
            created_at=datetime(2024, 9, 25),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Charming Ranch",
            location="Valley Springs",
            street="88 Ranch Road",
            price=620000,
            area=190,
            property_type="HOUSE",
            description="A charming ranch-style home with plenty of space for outdoor activities.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="1",
            build_year="1992",
            created_at=datetime(2025, 1, 4),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Victorian House",
            location="Historic District",
            street="456 Vintage Street",
            price=750000,
            area=250,
            property_type="HOUSE",
            description="A beautifully restored Victorian house with original architectural details.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="3",
            build_year="1900",
            created_at=datetime(2024, 5, 18),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Contemporary Loft",
            location="Downtown",
            street="45 Sunset Blvd",
            price=850000,
            area=220,
            property_type="HOUSE",
            description="A modern loft with sleek finishes and amazing city views.",
            transaction_type="SELL",
            floor="10",
            num_of_floors="15",
            build_year="2023",
            created_at=datetime(2025, 2, 7),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Chic Apartment",
            location="Lakeview",
            street="200 Lakeshore Drive",
            price=450000,
            area=160,
            property_type="HOUSE",
            description="A stylish apartment with a lakeside view, perfect for city dwellers.",
            transaction_type="SELL",
            floor="5",
            num_of_floors="10",
            build_year="2018",
            created_at=datetime(2025, 3, 15),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Penthouse Suite",
            location="Hilltop",
            street="99 Skyline Drive",
            price=2000000,
            area=400,
            property_type="HOUSE",
            description="A luxurious penthouse with panoramic views of the city and mountains.",
            transaction_type="SELL",
            floor="25",
            num_of_floors="25",
            build_year="2021",
            created_at=datetime(2025, 4, 3),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Country Home",
            location="Farmville",
            street="333 Green Acres Lane",
            price=600000,
            area=220,
            property_type="HOUSE",
            description="A peaceful country home with acres of farmland and fresh air.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="2",
            build_year="1998",
            created_at=datetime(2025, 5, 19),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Urban Studio",
            location="Riverwalk",
            street="12 Riverway Blvd",
            price=320000,
            area=100,
            property_type="HOUSE",
            description="A compact and trendy studio, perfect for young professionals.",
            transaction_type="SELL",
            floor="2",
            num_of_floors="4",
            build_year="2016",
            created_at=datetime(2025, 6, 9),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Vintage Villa",
            location="Hillcrest",
            street="144 Hilltop Road",
            price=1500000,
            area=350,
            property_type="HOUSE",
            description="A modern villa with a spacious backyard, pool, and luxurious interiors.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="2",
            build_year="2019",
            created_at=datetime(2025, 7, 21),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Cozy Cottage",
            location="Pine Forest",
            street="56 Pinewood Avenue",
            price=400000,
            area=130,
            property_type="HOUSE",
            description="A cozy cottage surrounded by pine trees, perfect for a quiet retreat.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="1",
            build_year="1992",
            created_at=datetime(2025, 8, 4),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Spacious Family Home",
            location="Lakewood",
            street="123 Pine Drive",
            price=550000,
            area=230,
            property_type="HOUSE",
            description="A spacious family home with large living spaces and a beautiful garden.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="2",
            build_year="2005",
            created_at=datetime(2025, 9, 14),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Luxury Ranch",
            location="Riverstone",
            street="777 Riverstone Road",
            price=950000,
            area=280,
            property_type="HOUSE",
            description="A luxury ranch with a large estate and stables, perfect for equestrians.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="2",
            build_year="2017",
            created_at=datetime(2025, 10, 22),
        ),
        Listing(
            client_id="d21568c9-1389-4cc2-a7b4-bee3fdfe55f4",
            title="Suburban Family House",
            location="Greenhill",
            street="303 Greenhill Road",
            price=500000,
            area=190,
            property_type="HOUSE",
            description="A comfortable family home with great schools in the neighborhood.",
            transaction_type="SELL",
            floor="1",
            num_of_floors="2",
            build_year="2010",
            created_at=datetime(2025, 11, 3),
        ),
    ]

    try:
        session.add(client_data)
        session.add_all(listing_data)
        await session.commit()

    except IntegrityError:
        print("Data was already inserted")

    except Exception as e:
        print(f"{e}")
        await session.rollback()

    finally:
        await session.close()


if __name__ == "__main__":
    asyncio.run(populate_db())
